DATA:
  name: "VisualGenom"
  img_size: 128
  num_classes: 8
MODEL:
  backbone: "big_resnet"
  g_cond_mtd: "W/O"
  d_cond_mtd: "W/O"
  apply_g_sn: True
  apply_d_sn: True
  z_dim: 120
  g_shared_dim: 128
  g_conv_dim: 96
  d_conv_dim: 96
LOSS:
  adv_loss: "hinge"
OPTIMIZATION:
  batch_size: 256
  g_lr: 0.00005
  d_lr: 0.0002
  beta1: 0.0
  beta2: 0.999
  d_updates_per_step: 2
  total_steps: 200000
PRE:
  apply_rflip: False
